kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

# Enable Ingress:

# nodes:
#   - role: control-plane
#     extraPortMappings:
#       - containerPort: 80
#         hostPort: 8080
#       - containerPort: 443
#         hostPort: 8443

#   - role: worker
#   - role: worker

# nodes:
#   - role: control-plane
#   - role: worker
#   - role: worker


nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /Users/jpaulraj/kind-development/dags   # Replace with your local directory
        containerPath: /mnt/hostpath  # Path inside the Kind container
  - role: worker
    extraMounts:
      - hostPath: /Users/jpaulraj/kind-development/dags  # Same local directory
        containerPath: /mnt/hostpath

