pcaf:
  target: dev
  outputs:
    dev:
      type: trino
      host: host.docker.internal
      user: admin
      #password: <password>
      port: 8081
      database: hive
      schema: pcaf
      threads: 1