apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
      - name: minio-storage
        emptyDir: {}
      containers:
      - name: minio
        image: osclimate/minio:1.0
        args:
        - server
        - /data
        - '--console-address=:9001'
        volumeMounts:
        - name: minio-storage
          mountPath: /data
        env:
        - name: MINIO_ROOT_USER
          value: "minioAdmin"
        - name: MINIO_ROOT_PASSWORD
          value: "minio1234"

        ports:
        - containerPort: 9000
          protocol: TCP
        - containerPort: 9001
          protocol: TCP
      initContainers:
      - name: configure-mc
        image: osclimate/minio:1.0
        command:
        - /bin/sh
        - -c
        - |
          mc alias set myminio http://localhost:9000 minioAdmin minio1234
          # mc admin config set myminio api web_cors="*"
          mc mb myminio/pcaf || echo "Bucket already exists"
        # env:
        # - name: MINIO_ROOT_USER
        #   value: "minioAdmin"
        # - name: MINIO_ROOT_PASSWORD
        #   value: "minio1234"
