# Use the official Python image from Docker Hub
FROM python:3.12-slim

# Set working directory inside the container
WORKDIR /app

# Copy your local Python script to the container
COPY app.py .

# Define the command to run the script
CMD ["python", "app.py"]