kind: Secret
apiVersion: v1
metadata:
  name: hive-metastore-secret
  namespace: osclimate
  labels:
    app: hive-metastore
stringData:
  AWS_ACCESS_KEY_ID: minioAdmin
  AWS_SECRET_ACCESS_KEY: minio1234
  DATABASE_DB: hivemetadb
  DATABASE_HOST: hive-metastore-db
  DATABASE_PASSWORD: hivemeta123$
  DATABASE_PORT: '5432'
  DATABASE_USER: hive