kind: Secret
apiVersion: v1
metadata:
  name: hive-metastore-secret
  namespace: osclimate
  labels:
    app: hive-metastore
data:
  AWS_ACCESS_KEY_ID: minioAdmin
  AWS_SECRET_ACCESS_KEY: minio1234
  POSTGRES_DB: hivemetadb
  POSTGRES_HOST: hive-metastore-db
  POSTGRES_PASSWORD: hivemeta123$
  POSTGRES_PORT: 9083
  POSTGRES_USER: hive
