kind: Secret
apiVersion: v1
metadata:
  name: hive-metastore-secret
  namespace: osclimate
  labels:
    app: hive-metastore
data:
  AWS_ACCESS_KEY_ID: bWluaW9BZG1pbg==
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM0
  DATABASE_DB: aGl2ZW1ldGFkYg==
  DATABASE_HOST: aGl2ZS1tZXRhc3RvcmUtZGI=
  DATABASE_PASSWORD: aGl2ZW1ldGExMjMk
  DATABASE_PORT: NTQzMg==
  DATABASE_USER: aGl2ZQ==
