# Use slim Python 3.12 as base image
FROM python:3.12-slim

# Set environment variables to avoid Python buffering and set UTF-8 encoding
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    build-essential \
    libpq-dev \
    python3-dev \
    curl \
    && pip install --upgrade pip \
    && pip install \
        requests \
        pendulum \
        sqlalchemy \
        trino[sqlalchemy] \
        boto3 \
        pandas \
        pycountry \
        pyarrow \
    && apt-get remove -y gcc build-essential \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# Copy your Python script
COPY dim_country.py .

# Set the default command
CMD ["python", "dim_country.py"]